// SPDX-License-Identifier: MIT
// Copyright (c) 2026-Present Robert Campbell

/// foundation.rhi.webgpu:texture - Texture over WGPUTexture.

module;
#include "Core/Prelude.h"
#include "WebGpuIncludes.h"

export module foundation.rhi.webgpu:texture;

import foundation.core;
import foundation.rhi;
import :api;
import :conversions;

using namespace foundation::core;

export namespace foundation::rhi::webgpu
{
    class WebGpuTexture final : public Texture
    {
    public:
        Status Initialize(const WebGpuApi& api, WGPUDevice device, const TextureDesc& textureDesc)
        {
            m_api = &api;
            desc = textureDesc;

            const WGPUTextureFormat format = ToWgpuTextureFormat(textureDesc.format);
            if (format == WGPUTextureFormat_Undefined &&
                textureDesc.format != TextureFormat::Undefined)
            {
                return ErrorCode::NotSupported; // format has no WebGPU equivalent
            }

            WGPUTextureDescriptor wgpuDesc = WGPU_TEXTURE_DESCRIPTOR_INIT;
            wgpuDesc.label = ToWgpuStringView(textureDesc.label);
            wgpuDesc.usage = ToWgpuTextureUsage(textureDesc.usage);
            // Mip chains are generated by the internal blit pass (no vkCmdBlitImage
            // shape in WebGPU): every mip must be renderable + samplable. Widen only
            // for 2D color formats the pass can actually target.
            if (textureDesc.mipLevelCount > 1 &&
                textureDesc.dimension == TextureDimension::Texture2D &&
                IsBlitCapableFormat(textureDesc.format))
            {
                wgpuDesc.usage |= WGPUTextureUsage_RenderAttachment |
                                  WGPUTextureUsage_TextureBinding;
            }
            wgpuDesc.dimension = ToWgpuTextureDimension(textureDesc.dimension);
            wgpuDesc.size.width = textureDesc.width;
            wgpuDesc.size.height = textureDesc.height;
            // WebGPU takes a block-compressed texture only in whole blocks (a 480 x 270 BC1 picture
            // was refused: "not a multiple of the block width (4) and height (4)"); Vulkan takes the
            // size in texels. The data already fills its last blocks (the cook repeats the edge
            // texels), so the texture is made at the size rounded up to whole blocks: sampled, the
            // picture spreads over at most three more edge rows or columns. Each level's write is
            // rounded the same way (WebGpuTransferBatch) and fits inside it.
            if (IsCompressed(textureDesc.format))
            {
                const u32 bw = BlockWidth(textureDesc.format);
                const u32 bh = BlockHeight(textureDesc.format);
                wgpuDesc.size.width = (wgpuDesc.size.width + bw - 1) / bw * bw;
                wgpuDesc.size.height = (wgpuDesc.size.height + bh - 1) / bh * bh;
            }
            // WebGPU folds array layers into depthOrArrayLayers (3D textures have no layers).
            wgpuDesc.size.depthOrArrayLayers =
                textureDesc.dimension == TextureDimension::Texture3D
                    ? textureDesc.depth
                    : textureDesc.arrayLayerCount;
            wgpuDesc.format = format;
            wgpuDesc.mipLevelCount = textureDesc.mipLevelCount;
            wgpuDesc.sampleCount = textureDesc.sampleCount;

            m_texture = api.wgpuDeviceCreateTexture(device, &wgpuDesc);
            return m_texture != nullptr ? Status(ErrorCode::Ok) : Status(ErrorCode::Unknown);
        }

        /// Wraps an EXTERNALLY-owned texture (the swapchain's current image): no release
        /// on destruction, the surface owns it.
        void WrapExternal(const WebGpuApi& api, WGPUTexture texture, const TextureDesc& textureDesc)
        {
            m_api = &api;
            m_texture = texture;
            m_ownsHandle = false;
            desc = textureDesc;
        }

        void Release()
        {
            if (m_texture != nullptr && m_ownsHandle)
            {
                m_api->wgpuTextureRelease(m_texture);
            }
            m_texture = nullptr;
        }

        [[nodiscard]] WGPUTexture Handle() const { return m_texture; }

    private:
        const WebGpuApi* m_api = nullptr;
        WGPUTexture m_texture = nullptr;
        bool m_ownsHandle = true;
    };
}
