// SPDX-License-Identifier: MIT
// Copyright (c) 2026-Present Robert Campbell

// The AssiduousEngine logo (Data/Assets/branding/assiduous-logo.svg) baked into the player as its
// SVG text (EmbeddedEngineLogo.cpp, generated by EmbedBinary.cmake): the default loading screen
// shows it when a game names no loading document. Include it in a global module fragment, so the
// symbols keep the generated file's linkage.
#pragma once

extern const unsigned char g_embeddedEngineLogo[];
extern const unsigned long long g_embeddedEngineLogoSize;
